# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'centos/6'          # (d1)
  config.vm.define :spring do |node|
    node.vm.hostname = 'spring-boot'  # (d2)
    node.vm.network :private_network, # (d3)
                    ip: '192.168.88.30'
    node.vm.network :forwarded_port,  # (d4)
                    guest: 80,
                    host: 8080,
                    auto_correct: true
  end
  config.vm.provision :shell,         # (d5)
                      path: 'bootstrap.sh'
end
